### ISSUE TITLE
Typo in the repo name

### ISSUE THREAD

**Issue by ahmedsameha1** [CodingChallengesFYI/SharedSolutions#279]
I think that the repo name should be: CodingChallengesFYI, not CodingChallegesFYI.

**Comment by elliotwutingfeng** [comment]
I don't like mispell as well. The biggest risk would be a bad actor claiming the old name <https://docs.github.com/en/organizations/managing-organization-settings/renaming-an-organization>.

**Comment by JohnCrickett** [comment]
Fixed.
